# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: sms_api_production
  driver: ruby
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  error_handler: Proc.new { |method:, returning:, exception:|
    Rails.logger.error "Redis error: #{exception.class} - #{exception.message}"
    Rails.logger.error exception.backtrace.join("\n")
  }
