development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost:27017/sms_api_development" %>
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost:27017/sms_api_test" %>
      options:
        server_selection_timeout: 5
        retry_writes: false

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost:27017/sms_api_production" %>
      options:
        server_selection_timeout: 5
